-- SQLite
CREATE TABLE IF NOT EXISTS ACCOUNT_HOLDER(
    ID INTEGER  PRIMARY KEY AUTOINCREMENT,
    FNAME TEXT NOT NULL,
    LNAME TEXT NOT NULL,
    DATE_MEMBER DATE NOT NULL,
    PIN CHAR(4) NOT NULL,
    UNIQUE(FNAME,LNAME)
);
CREATE TABLE IF NOT EXISTS BANK_ACCOUNT(
    ID INTEGER  PRIMARY KEY AUTOINCREMENT,
    OWNER INTEGER,
    ACCOUNTID INTEGER,
    AMOUNT NUMERIC(10,2) NOT NULL,
    DATE_CREATED DATE NOT NULL,
    FOREIGN KEY (OWNER) REFERENCES ACCOUNT_HOLDER(ID) ON DELETE CASCADE,
    FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNT(ID) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS TRANSACTION_HISORY(
    ID INTEGER  PRIMARY KEY AUTOINCREMENT,
    ACCOUNT INTEGER,
    TRANS_VAL NUMERIC(4,2) NOT NULL,
    DATE_OF_TRANS DATE, 
    FOREIGN KEY (ACCOUNT) REFERENCES BANK_ACCOUNT(ID) ON DELETE CASCADE 
);
CREATE TABLE IF NOT EXISTS ACCOUNT(
    ID INTEGER  PRIMARY KEY AUTOINCREMENT,
    ACCOUNT_DESCIPTION TEXT NOT NULL,
    UNIQUE(ID,ACCOUNT_DESCIPTION)
);
INSERT INTO ACCOUNT(ACCOUNT_DESCIPTION)  VALUES('Savings');
INSERT INTO ACCOUNT(ACCOUNT_DESCIPTION)  VALUES('Checkings');
INSERT INTO ACCOUNT_HOLDER(FNAME,LNAME,DATE_MEMBER, PIN)  VALUES('John','Doe','2023-01-01','1234');
INSERT INTO BANK_ACCOUNT(ID, OWNER ,ACCOUNTID,AMOUNT ,DATE_CREATED)  VALUES(100,1,1,456.00,'2023-01-01');
INSERT INTO BANK_ACCOUNT(OWNER,ACCOUNTID,AMOUNT,DATE_CREATED)  VALUES(1,2,1000.00,'2023-01-01');
INSERT INTO ACCOUNT_HOLDER(FNAME,LNAME,DATE_MEMBER, PIN)  VALUES('Jo-annna','Doe','2023-01-01','4321');
INSERT INTO BANK_ACCOUNT(OWNER,ACCOUNTID,AMOUNT ,DATE_CREATED)  VALUES(2,1,250.00,'2023-01-01');
INSERT INTO BANK_ACCOUNT(OWNER,ACCOUNTID,AMOUNT,DATE_CREATED)  VALUES(2,2,800.00,'2023-01-01');
INSERT INTO ACCOUNT_HOLDER(FNAME,LNAME,DATE_MEMBER, PIN)  VALUES('Mike','Kistosiki','2023-01-01','1111');
INSERT INTO BANK_ACCOUNT(OWNER,ACCOUNTID,AMOUNT ,DATE_CREATED)  VALUES(3,1,250.00,'2023-01-01');
INSERT INTO BANK_ACCOUNT(OWNER,ACCOUNTID,AMOUNT,DATE_CREATED)  VALUES(3,2,800.00,'2023-01-01');